version: '3.9'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 8080:8080
    # -tオプションと同じ。bashがすぐに終了するのを防ぐ
    tty: true
    volumes:
      - ./api:/workspace:cashed
  
  web:
    container_name: web
    build: 
      context: ./web
      target: base
    ports:
      - 3000:3000
    # -tオプションと同じ。bashがすぐに終了するのを防ぐ
    tty: true
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    volumes:
      - ./web:/workspace:cashed
    depends_on:
      - api
