version: '3.9'
services:
  api:
    container_name: api
    build: 
      context: ./api
      target: production
    ports:
      - 8080:8080
    # コンテナ起動を継続させるため、-tの代わりに使用する。
    tty: true
    volumes:
      - ./api:/workspace:cashed
  
  web:
    container_name: web
    build: 
      context: ./web
      target: production
      args:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    ports:
      - 3000:80
    # コンテナ起動を継続させるため、-tの代わりに使用する。
    tty: true
    volumes:
      - ./web:/workspace:cashed
    depends_on:
      - api
